name:                yampaSDLTemplate
version:             0.1.0.0
github:              "githubuser/yampaSDLTemplate"
license:             BSD-3-Clause
author:              "yokoP"
maintainer:          "syouzanponkikki@yahoo.co.jp"
copyright:           "2025 Teruhisa Yokoyama"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/syouzan420/yampaSDLTemplate#readme>

dependencies:
- base >= 4.7 && < 5
- sdl2
- sdl2-ttf
- sdl2-gfx
- sdl2-image
- sdl2-mixer
- Yampa
- time
- containers
- text
- random
- simple-affine-space

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  yampaSDLTemplate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yampaSDLTemplate 

tests:
  yampaSDLTemplate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yampaSDLTemplate
